server:
  servlet:
    context-path: /gestorAPI/api

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverclassName: org.h2.Driver

h2:
  console:
    enabled: true
    path: /h2-console

